# Generated by Django 4.0.3 on 2022-05-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('disease_current', models.CharField(max_length=100)),
                ('progress_disease', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('bite', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('conclusion', models.CharField(max_length=100)),
                ('date_record', models.DateField()),
                ('next_date', models.DateField()),
                ('prosthesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.prosthesis')),
            ],
        ),
    ]
