# Generated by Django 4.0.3 on 2022-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage1', '0002_alter_stages_1_prosthesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages_1',
            name='date_record',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stages_1',
            name='next_date',
            field=models.DateField(null=True),
        ),
    ]
