# Generated by Django 4.0.3 on 2022-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_birth',
            field=models.CharField(max_length=100),
        ),
    ]
