# Generated by Django 4.0.3 on 2022-05-31 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_patientcard_client_alter_prosthesis_card'),
        ('stage3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages_3',
            name='prosthesis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.prosthesis'),
        ),
    ]
