# Generated by Django 4.0.3 on 2022-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_construction_type_prost'),
        ('stage4', '0003_alter_stages_4_date_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages_4',
            name='materials',
        ),
        migrations.AddField(
            model_name='stages_4',
            name='materials',
            field=models.ManyToManyField(to='materials.materials'),
        ),
    ]
