# Generated by Django 4.0.3 on 2022-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage4', '0004_remove_stages_4_materials_stages_4_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages_4',
            name='materials',
        ),
        migrations.AddField(
            model_name='stages_4',
            name='material_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stages_4',
            name='material_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stages_4',
            name='material_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stages_4',
            name='material_4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
